'use client';
import { useState } from 'react';
import { BiCoffee, BiUser, BiJoystick, BiHive } from 'react-icons/bi';

import ButtonDefault from '@/components/Buttons/ButtonDefault';
import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';

import { useTabsStore } from '@/store/tabs';
import { GlobalStyles } from '@/styles/global';
import { Inter } from 'next/font/google';
import { usePathname, useRouter } from 'next/navigation';
import { v4 as uuidv4, v5 as uuidv5 } from 'uuid';

import StyledJsxRegistry from './registry';
import { Container, Main } from './styles';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface ItemsProps {
  id: number;
  title: string;
  name: string;
  to: string;
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const router = useRouter();
  const v4Id = uuidv4();

  const {
    state: { tabs },
    actions: { addTabs }
  } = useTabsStore();

  function handleOnClick(name: string) {
    console.log('Clicou', name);

    addTabs({
      id: v4Id,
      name,
      title: name,
      to: name + '/' + String(tabs.length + 1)
    });

    // setItems([
    //   ...items,
    //   {
    //     id: items.length,
    //     name,
    //     title: 'Dashboard',
    //     to: name + '/' + String(items.length + 1)
    //   }
    // ]);

    router.push(`${name}` + '/' + String(tabs.length + 1));
  }
  console.log('ITEMS', tabs);
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <Container>
            <Header />
            <Main>
              <Sidebar
                handleOnClick={handleOnClick}
                path={pathname}
                menus={[
                  {
                    to: '/dashboard',
                    name: 'Dashboard',
                    icon: BiCoffee
                  },
                  {
                    to: '/servicos',
                    name: 'Serviços',
                    icon: BiUser
                  },
                  {
                    to: '/equipe',
                    name: 'Equipe',
                    icon: BiJoystick
                  },
                  {
                    to: '/fluxo',
                    name: 'Fluxo',
                    icon: BiHive,
                    submenu: ['listagem', 'boletos', 'admin']
                  },
                  {
                    to: '/gestao',
                    name: 'Gestao',
                    icon: BiHive,
                    submenu: ['listagem', 'boletos', 'admin']
                  }
                ]}
              />

              <div className="contentMain">
                <div className="sidebarItems">
                  {tabs.map((row) => (
                    <ButtonDefault
                      typeButton={pathname === row.to ? 'primary' : 'light'}
                      onClick={() => router.push(row.to)}
                      key={row.id}
                    >
                      {row.title + '_' + row.to.charAt(row.to.length - 1)}
                    </ButtonDefault>
                  ))}
                </div>
                {children}
              </div>
            </Main>
          </Container>
          <GlobalStyles />
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
