'use client';
import { useEffect, useState } from 'react';
import { BiCoffee, BiUser, BiJoystick, BiHive } from 'react-icons/bi';

import ButtonDefault from '@/components/Buttons/ButtonDefault';
import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';

import { useTabsStore } from '@/store/tabs';
import { GlobalStyles } from '@/styles/global';
import { Inter } from 'next/font/google';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { v4 as uuidv4 } from 'uuid';

import StyledJsxRegistry from './registry';
import { Container, Main } from './styles';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface ItemsProps {
  id: number;
  title: string;
  name: string;
  to: string;
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const router = useRouter();
  const params = useSearchParams();
  const v4Id = uuidv4();

  const {
    state: { tabs },
    actions: { addTabs }
  } = useTabsStore();

  function hasPath(name: string) {
    const nameLenght = name.length;
    const newPath = pathname.substring(0, nameLenght);
    // console.log('newPath', newPath);
    return newPath;
  }

  function handleOnClick(name: string) {
    addTabs({
      id: v4Id,
      name: name + '/' + String(tabs.length + 1),
      title: name + '_' + String(tabs.length + 1),
      to: name + '/' + String(tabs.length + 1)
    });

    // setItems([
    //   ...items,
    //   {
    //     id: items.length,
    //     name,
    //     title: 'Dashboard',
    //     to: name + '/' + String(items.length + 1)
    //   }
    // ]);

    router.push(`${name}` + '/' + String(tabs.length + 1));
  }

  // useEffect(() => {
  //   const url = `${pathname}`;
  //   console.log('URL', url);
  //   // You can now use the current URL
  //   // ...
  // }, [pathname, searchParams]);
  console.log('TABS', tabs);
  // console.log('PARMAS', params.has('name'));
  // console.log('HAS-PATH', hasPath(name + '/' + String(tabs.length + 1)));

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <Container>
            <Header />
            <Main>
              <Sidebar
                handleOnClick={handleOnClick}
                path={pathname}
                menus={[
                  // {
                  //   to: '/dashboard',
                  //   name: 'Dashboard',
                  //   icon: BiCoffee
                  // },
                  {
                    to: '/service',
                    name: 'Serviços',
                    icon: BiUser
                  },
                  {
                    to: '/equipe',
                    name: 'Equipe',
                    icon: BiJoystick
                  },
                  {
                    to: '/fluxo',
                    name: 'Fluxo',
                    icon: BiHive,
                    submenu: ['listagem', 'boletos', 'admin']
                  },
                  {
                    to: '/gestao',
                    name: 'Gestao',
                    icon: BiHive,
                    submenu: ['listagem', 'boletos', 'admin']
                  }
                ]}
              />

              <div className="contentMain">
                <div className="sidebarItems">
                  {tabs.map((row) => (
                    <ButtonDefault
                      typeButton={hasPath(row.name) === row.name ? 'primary' : 'light'}
                      onClick={() => router.push(row.to)}
                      key={row.id}
                    >
                      {row.title}
                    </ButtonDefault>
                  ))}
                </div>
                {children}
              </div>
            </Main>
          </Container>
          <GlobalStyles />
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
